/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liux_example_jnitest_JniTest */

#ifndef _Included_com_liux_example_jnitest_JniTest
#define _Included_com_liux_example_jnitest_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liux_example_jnitest_JniTest
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_liux_example_jnitest_JniTest_sayHello
  (JNIEnv *, jclass);

/*
 * Class:     com_liux_example_jnitest_JniTest
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_liux_example_jnitest_JniTest_stringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
